In [2]:
# ndarray的shape 和 dtype
import numpy as np

data1=[84,23,5,6,3,5,3,5,3]
data2=[834,235,15,36,35,51,3,54,3]
nda1=np.array(data1)

nda1.shape

(9,)

In [16]:
# 按距离 随机生成
r1=np.arange(20,dtype=np.int64)
r1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
points=np.arange(-1,1,0.1)

# 从一个坐标向量中返回一个坐标矩阵
x,y=np.meshgrid(points,points)
x

array([[-1.00000000e+00, -9.00000000e-01, -8.00000000e-01,
        -7.00000000e-01, -6.00000000e-01, -5.00000000e-01,
        -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
        -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
         2.00000000e-01,  3.00000000e-01,  4.00000000e-01,
         5.00000000e-01,  6.00000000e-01,  7.00000000e-01,
         8.00000000e-01,  9.00000000e-01],
       [-1.00000000e+00, -9.00000000e-01, -8.00000000e-01,
        -7.00000000e-01, -6.00000000e-01, -5.00000000e-01,
        -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
        -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
         2.00000000e-01,  3.00000000e-01,  4.00000000e-01,
         5.00000000e-01,  6.00000000e-01,  7.00000000e-01,
         8.00000000e-01,  9.00000000e-01],
       [-1.00000000e+00, -9.00000000e-01, -8.00000000e-01,
        -7.00000000e-01, -6.00000000e-01, -5.00000000e-01,
        -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
        -1.00000000e-01, -2.2

In [6]:
np.eye(4,dtype=np.int64)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [15]:
# 正太分布登数据
r2=np.random.randn(4,4)
r2

array([[-0.87342678, -1.03638483,  1.84730181,  0.31133215],
       [ 0.30577882, -0.90293428,  0.79430347, -0.48578177],
       [ 0.22830689,  0.86612594,  0.07503103,  0.28941002],
       [ 1.2285727 , -0.07357942,  0.18062972,  0.23526329]])

In [20]:
# 过滤 索引
r1[r1>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
# where 过滤
ndaifa=np.array(['a','b','c','d','e'])
ndaifb=np.array(['A','B','C','D','E'])
ndaif=np.array([True,False,False,True,True])
nadif_result=np.where(ndaif,ndaifa,ndaifb)
nadif_result



array(['a', 'B', 'C', 'd', 'e'], dtype='<U1')

In [ ]:
# 元素级数组函数

numpy.square(r1)


In [10]:
arn2=np.random.randn(5,4)
print(arn2)
# 算术平均值
arn2.mean()

[[ 1.81530313  1.28573125 -1.19381672 -0.50085882]
 [-0.47445463  0.71762664 -0.02720454 -0.50047648]
 [-0.2118844   2.03581532  1.53504961  1.13042662]
 [-1.19418246  0.62175085 -0.86354055 -0.23390966]
 [ 0.27635161 -0.79831558 -0.17378183  0.5611534 ]]


0.19033913830750246